server:
  port: 30000
spring:
  profiles:
    active: '@activatedYml@'
  application:
    name: snake-gateway-server
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 10000
        connect-timeout: 3000
      routes:
        - id: k8sDnsRouter
          order: -2147483648
          uri: https://www.a.com
          predicates:
            - Path=/{serverName}-api/**
          filters: k8sDnsFilter
        - id: localRoute
          order: -2147483648
          uri: https://www.b.com
          predicates:
            - Path=/l-*/**
          filters: localFilter
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com:
      snake:
        gateway: info
web:
  core:
    application-name: ${spring.application.name}
    server-port: ${server.port}
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  token-prefix: Bearer
  # token 有效期（单位：秒） -1 代表永久有效 这里设置为1小时
  timeout: 3600
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: true
  # 是否尝试从 header 里读取 Token
  is-read-head: true
  # 是否开启自动续签
  auto-renew: true
  # jwt秘钥
  jwt-secret-key: adfdfdsdasdasifdfdffhueuiwyudfdfddfdfsfsdfrfewbfjsdafjk
