user-auth:
  exclude-paths:
    - /favicon.ico
    - /login
    - /register
sa-token:
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 15
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 16379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 30s
base:
  url:
    snake-system-server: http://localhost:31001/
gateway:
  k8s-servers:
    - application-name: snake-system-api
      host: 127.0.0.1
      port: 31001